// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgdlmewficjsejmctxkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnZGxtZXdmaWNqc2VqbWN0eGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NjA5NDQsImV4cCI6MjA1ODAzNjk0NH0.SOKqvksEutW47L2mq8krvY0EFyvs3nrKBQ7sTeMtASk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);